version: '3.1'

services:
    mongo-primary:
        image: mongo
        container_name: chimeradb-primary
        hostname: chimeradb-primary
        restart: always
        command: --replSet crs --bind_ip_all --keyFile /home/mongod.keyfile
        expose:
          - 27017
        volumes:
            - ./docker/mongo/initdb:/docker-entrypoint-initdb.d/
            - ./docker/mongo:/home
            - mongodata-primary:/data/db
        env_file:
            - ./env/.env

    mongo-secondary:
        image: mongo
        container_name: chimeradb-ares
        hostname: chimeradb-ares
        restart: always
        command: --replSet crs --bind_ip_all --keyFile /home/mongod.keyfile
        expose:
          - 27017
        volumes:
            - ./docker/mongo/initdb:/docker-entrypoint-initdb.d/
            - ./docker/mongo:/home
            - mongodata-ares:/data/db
        env_file:
          - ./env/.env
   
volumes:
    mongodata-primary:
    mongodata-ares:
    mongodata-boreas:
