version: '3.4'

x-environment: &environment
  - ./env/.env.schema
  - ./env/.env.defaults
  - ./env/.env

x-mongo-rs-node: &mongo-rs-node
  build:
    context: docker/mongo
    dockerfile: Dockerfile
  image: chimeradb
  restart: always
  command: --replSet crs --bind_ip_all --keyFile /home/mongod.keyfile
  expose:
    - 27017
  env_file: *environment
  environment:
    - CHIMERADB_REPLICASET_PRIMARY=true

services:

  nestjs:
    build:
      context: .
      dockerfile: docker/nestjs/Dockerfile
    image: chimera
    container_name: chimera
    hostname: chimera
    command: yarn start:production
    ports:
      - 3000:3000
    volumes:
      - nestjs_node_modules:/home/node_modules/
    env_file: *environment

  mongo-primary:
    <<: *mongo-rs-node
    container_name: chimeradb-primary
    hostname: chimeradb-primary
    volumes:
      - primary_mongodata:/data/db

  mongo-secondary:
    <<: *mongo-rs-node
    container_name: chimeradb-ares
    hostname: chimeradb-ares
    volumes:
      - ares_mongodata:/data/db

  mongo-arbiter:
    <<: *mongo-rs-node
    container_name: chimeradb-boreas
    hostname: chimeradb-boreas
    volumes:
      - boreas_mongodata:/data/db

volumes:
  nestjs_node_modules:
  primary_mongodata:
  ares_mongodata:
  boreas_mongodata:
